# clang-mingw-x64.cmake

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x64)

set(LLVM_MINGW_ROOT /opt/llvm-mingw)
set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)

set(CMAKE_C_COMPILER ${LLVM_MINGW_ROOT}/bin/clang)
set(CMAKE_CXX_COMPILER ${LLVM_MINGW_ROOT}/bin/clang++)

set(CMAKE_C_COMPILER_TARGET ${TOOLCHAIN_PREFIX})
set(CMAKE_CXX_COMPILER_TARGET ${TOOLCHAIN_PREFIX})

set(CMAKE_RC_COMPILER ${LLVM_MINGW_ROOT}/bin/llvm-windres)

set(CMAKE_AR ${LLVM_MINGW_ROOT}/bin/llvm-ar)
set(CMAKE_RANLIB ${LLVM_MINGW_ROOT}/bin/llvm-ranlib)
set(CMAKE_NM ${LLVM_MINGW_ROOT}/bin/llvm-nm)

set(CMAKE_LINKER ${LLVM_MINGW_ROOT}/bin/ld.lld)

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)

set(IS_CLANG_MINGW ON)
