if(IS_DX8)
    message(STATUS "Selected renderer: DirectX 8 (PC_R1)")
    set(RENDERER_LIB xrRender_R1)
    set(RENDERER_DIR Layers/xrRenderPC_R1)
elseif(IS_DX9)
    message(STATUS "Selected renderer: DirectX 9 (PC_R2)")
    set(RENDERER_LIB xrRender_R2)
    set(RENDERER_DIR Layers/xrRenderPC_R2)
elseif(IS_DX10)
    message(STATUS "Selected renderer: DirectX 10 (PC_R3)")
    set(RENDERER_LIB xrRender_R3)
    set(RENDERER_DIR Layers/xrRenderPC_R3)
elseif(IS_DX11)
    message(STATUS "Selected renderer: DirectX 11 (PC_R4)")
    set(RENDERER_LIB xrRender_R4)
    set(RENDERER_DIR Layers/xrRenderPC_R4)
else()
    message(FATAL_ERROR "No renderer selected")
endif()
