<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <xrBinRootDir>.\..\_build\bin\</xrBinRootDir>
    <xrBinPlugRootDir>.\..\_build\bin_plugs\</xrBinPlugRootDir>
    <xrLibRootDir>.\..\_build\lib\</xrLibRootDir>
    <xrBinDir>$(xrBinRootDir)$(Configuration)\</xrBinDir>
    <xrBinPlugDir>$(xrBinPlugRootDir)$(Configuration)\</xrBinPlugDir>
    <xrLibDir>$(xrLibRootDir)$(Configuration)\</xrLibDir>
    <xrIntDir>.\..\_build\intermediate\$(Configuration)\</xrIntDir>
    <xrSdkDir>.\..\sdk\</xrSdkDir>
    <xrGameDir>.\..\_build\_game\</xrGameDir>
    <xrGameBinDir>..\_build\_game\bin\</xrGameBinDir>
    <xr3rdPartyDir>.\3rd party\</xr3rdPartyDir>
    <dxSdkDir>..\sdk\include\dxsdk\</dxSdkDir>
  </PropertyGroup>
  <PropertyGroup>
    <IncludePath>.\..\src\3rd party;.\3rd party\icu\include;$(IncludePath);..\sdk\include;..\sdk\include\OpenAutomate;..\sdk\include\nvapi;..\sdk\include\dxsdk</IncludePath>
    <OutDir>..\_build\_game\bin_dbg\</OutDir>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <MultiProcessorCompilation>true</MultiProcessorCompilation>
      <BufferSecurityCheck>false</BufferSecurityCheck>
      <Optimization>Full</Optimization>
      <InlineFunctionExpansion>Default</InlineFunctionExpansion>
      <FloatingPointModel>Precise</FloatingPointModel>
      <UndefinePreprocessorDefinitions>USE_LUAJIT_ONE</UndefinePreprocessorDefinitions>
      <PreprocessorDefinitions>_VC80_UPGRADE=0x0710;_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <FavorSizeOrSpeed>Speed</FavorSizeOrSpeed>
      <DebugInformationFormat>None</DebugInformationFormat>
    </ClCompile>
    <Link>
      <LargeAddressAware>true</LargeAddressAware>
      <RandomizedBaseAddress>false</RandomizedBaseAddress>
      <GenerateDebugInformation>false</GenerateDebugInformation>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="xrBinRootDir">
      <Value>$(xrBinRootDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="xrBinPlugRootDir">
      <Value>$(xrBinPlugRootDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="xrLibRootDir">
      <Value>$(xrLibRootDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="xrBinDir">
      <Value>$(xrBinDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="xrBinPlugDir">
      <Value>$(xrBinPlugDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="xrLibDir">
      <Value>$(xrLibDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="xrIntDir">
      <Value>$(xrIntDir)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="xrSdkDir">
      <Value>..\sdk\</Value>
    </BuildMacro>
    <BuildMacro Include="xrGameDir">
      <Value>..\_build\_game\</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="xrGameBinDir">
      <Value>..\_build\_game\bin\</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="xr3rdPartyDir">
      <Value>3rd party\</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="dxSdkDir">
      <Value>..\sdk\include\dxsdk\</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
  </ItemGroup>
</Project>